package ai

import (
	"time"
)

// TokensUsed represents the token usage for an AI request
type TokensUsed struct {
	Input  int `json:"input"`
	Output int `json:"output"`
}

// AIReviewReport represents a weekly review report generated by AI
type AIReviewReport struct {
	ID                string     `json:"id"`
	UserID            string     `json:"userId"`
	WeekStart         string     `json:"weekStart"`
	WeekEnd           string     `json:"weekEnd"`
	Summary           string     `json:"summary"`
	GoodPoints        []string   `json:"goodPoints"`
	ImprovementPoints []string   `json:"improvementPoints"`
	Advice            []string   `json:"advice"`
	TokensUsed        TokensUsed `json:"tokensUsed"`
	CreatedAt         time.Time  `json:"createdAt"`
}

// AskResponse represents the response from an AI question
type AskResponse struct {
	Answer      string     `json:"answer"`
	Suggestions []string   `json:"suggestions"`
	TokensUsed  TokensUsed `json:"tokensUsed"`
}

// GenerateReviewInput represents the input for generating a review
type GenerateReviewInput struct {
	WeekStart string `json:"weekStart"`
	WeekEnd   string `json:"weekEnd"`
}

// AskInput represents the input for asking a question
type AskInput struct {
	Question string `json:"question"`
	Context  string `json:"context,omitempty"`
}

// ReviewFilter represents filters for listing review reports
type ReviewFilter struct {
	StartDate *string
	EndDate   *string
}

// TimeEntryData represents time entry data for AI analysis
type TimeEntryData struct {
	Description string    `json:"description"`
	ProjectName string    `json:"projectName"`
	Duration    string    `json:"duration"`
	StartTime   time.Time `json:"startTime"`
	EndTime     time.Time `json:"endTime"`
}

// LearningRecordData represents learning record data for AI analysis
type LearningRecordData struct {
	Title   string `json:"title"`
	Content string `json:"content"`
	GoalTag string `json:"goalTag,omitempty"`
}

// ReviewData represents aggregated data for review generation
type ReviewData struct {
	TimeEntries     []TimeEntryData      `json:"timeEntries"`
	LearningRecords []LearningRecordData `json:"learningRecords"`
}

// ParsedReviewResponse represents the parsed response from Claude for review generation
type ParsedReviewResponse struct {
	Summary           string   `json:"summary"`
	GoodPoints        []string `json:"goodPoints"`
	ImprovementPoints []string `json:"improvementPoints"`
	Advice            []string `json:"advice"`
}
